spring:
  application:
    name: shared
  threads:
    virtual:
      enabled: true

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    logging:
      endpoint: http://localhost:4318/v1/logs
  tracing:
    sampling:
      probability: ${OTEL_TRACING_SAMPLING_PROBABILITY:1.0}
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.namespace: ${OTEL_SERVICE_NAMESPACE:springboot3.5-otel}
      service.version: ${OTEL_SERVICE_VERSION:1.0.0}
      deployment.environment: ${OTEL_DEPLOYMENT_ENVIRONMENT:local}
  observations:
    annotations:
      enabled: true

logging:
  level:
    com.example: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
