spring:
  application:
    name: hello-service
  config:
    import:
      - "optional:classpath:application-otel.yaml"
      - "optional:classpath:application-kafka.yaml"

server:
  port: 18080

user:
  service:
    url: http://localhost:18081

greeting:
  service:
    url: http://localhost:18082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.apache.kafka: WARN
    org.apache.kafka.clients.NetworkClient: ERROR
    org.springframework.kafka: WARN
