spring:
  application:
    name: greeting-service
  config:
    import: "optional:classpath:application-otel.yaml"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

server:
  port: 18082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
